version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Post Building...
      - echo deleting unnecessary files
      - rm -rf public
      - rm -rf src
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
