version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_lts.x |  -E bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
